sudo: false
language: generic

env:
    - SW=$HOME/sw PATH=$SW/bin:$PATH CFLAGS=-I$SW/include LDFLAGS=-L$SW/lib LD_LIBRARY_PATH=$SW/qt/lib:$SW/lib PKG_CONFIG_PATH=$SW/lib/pkgconfig QMAKE=$SW/qt/bin/qmake QT_PLUGIN_PATH=$sw/qt/plugins

before_install:
    - curl https://download.calibre-ebook.com/travis/sw-linux.tar.xz | tar xJ -C $HOME
    - $QMAKE -query
    - python -c "import os, sys; os.environ['QT_DEBUG_PLUGINS']='1'; from PyQt5.Qt import *; print QLibraryInfo.location(QLibraryInfo.PluginsPath); fmts = map(str, QImageReader.supportedImageFormats()); print fmts; sys.exit('jpg' not in fmts)"
    - python setup.py bootstrap --ephemeral
script: python setup.py test
