sudo: false
language: generic

env:
    - SW=$HOME/sw PATH=$SW/bin:$PATH CFLAGS=-I$SW/include LDFLAGS=-L$SW/lib LD_LIBRARY_PATH=$SW/qt/lib:$SW/lib PKG_CONFIG_PATH=$SW/lib/pkgconfig QMAKE=$SW/qt/bin/qmake QMAKESPEC=$SW/qt/mkspecs/linux-g++

before_install:
    - curl https://download.calibre-ebook.com/travis/sw-linux.tar.xz | tar xJ -C $HOME
    - echo '[Paths]\nPrefix = ..' > $SW/qt/bin/qt.conf
    - cat $SW/qt/bin/qt.conf
    - python setup.py bootstrap --ephemeral
script: python setup.py test
